name: CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-Line script
      run: echo Hello, world!
    - name: Run a multi-Line sdript
      run: |
        echo Add other actions to build,
        echo test, and deploy you project.
